AppBundle\Entity\Task:
    type: entity
    table: task
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        status:
            type: boolean
            nullable: false
        dateCreated:
            type: date
            nullable: false
            column: date_created
    lifecycleCallbacks: {  }
